server:
  port: 9090
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        #配置feign接口所在包，使用debug模式
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.example.mallproject.feign: debug
